---
namespace: "pystol"
name: "actions"
version: "0.8.5"
description: "Pystol native actions"
authors: ["Carlos Camacho>"]
license: ["Apache-2.0"]
readme: README.md
tags:
  - pystol
  - pystol_actions
  - fault_injection
  - chaos_engineering
  - pingtest
repository: "https://github.com/pystol/pystol-galaxy"
homepage: "https://www.pystol.org"
documentation: "https://docs.pystol.org"
issues: "https://github.com/pystol/pystol-galaxy/issues"
